project:
  type: website
  output-dir: docs

website:
  title: "Salmon resource predictions"
  navbar:
    left:
      - text: "Home" 
        href: index.qmd
      - text: "Sliders"
        href: Sliders.qmd
      - text: "Map from field data"
        href: Exploits_map.qmd 
      - text: "Map from HydroSHEDs"
        href: Exploits_map2.qmd 

format:
  html:
    theme: sandstone
    css: styles.css
    toc: false


