project:
  type: website
  output-dir: docs

website:
  title: "Salmon resource predictions"
  navbar:
    left:
      - text: "Home" 
        href: index.qmd
      - text: "Watersheds"
        menu:
        - text: "Exploits River Watershed"
          href: Exploits_map.qmd 
        - text: "Rocky River Watershed"
          href: Rocky_map.qmd
        - text: "Terra Nova River Watershed"
          href: TerraNova_map.qmd
      - text: "Sliders"
        href: Sliders.qmd
        
format:
  html:
    theme: sandstone
    toc: false


